# Himanshi Notebook

In [10]:
import numpy as np
import pandas as pd

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df = pd.read_csv('covid_toy.csv')

In [13]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [14]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
65   69  Female  102.0    Mild  Bangalore
89   46    Male  103.0  Strong  Bangalore
32   34  Female  101.0  Strong      Delhi
51   11  Female  100.0  Strong    Kolkata
96   51  Female  101.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
78   11    Male  100.0    Mild  Bangalore
4    65  Female  101.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata
6    14    Male  101.0  Strong  Bangalore
69   73  Female  103.0    Mild      Delhi

[80 rows x 5 columns]

# Before column Transformer

In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [9]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [12]:
from sklearn.preprocessing import OneHotEncoder

# Use sparse_output instead of sparse
ohe = OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])  # use transform, not fit_transform

In [13]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [14]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# After column transformer

In [16]:
from sklearn.compose import ColumnTransformer

In [17]:
print(data.columns)

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender','city'])
], remainder='passthrough')

In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load your dataset
data = pd.read_csv("covid_toy.csv")

# Separate features and target
X = data.drop("has_covid", axis=1)   # all columns except target
y = data["has_covid"]                # target column

# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Now you can use your transformer
transformer.fit_transform(X_train).shape]
transformer.fit_transform(X_te